services:
  db:
    image: postgres:15-alpine
    # Load secrets directly from the .env file
    env_file:
      - .config/.env
    # Notice: NO 'ports' section here. The DB is completely isolated from the outside world.
    networks:
      - oref-inner-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    env_file:
      - .config/.env
    depends_on:
      - db
    networks:
      - oref-inner-net
    restart: always

volumes:
  pgdata:

# Defining a custom bridge network keeps the traffic securely contained
networks:
  oref-inner-net:
    driver: bridge
