services:
    db:
        image: postgres:16-alpine
        env_file:
            - .config/.env
        networks:
            - oref-inner-net
        volumes:
            - farsi:/var/lib/postgresql/data
        restart: always

    app:
        build: ./server
        env_file:
            - .config/.env
        volumes:
            - ./.config:/app/.config:ro
        depends_on:
            - db
        networks:
            - oref-inner-net
        restart: always

volumes:
    farsi:

networks:
    oref-inner-net:
        driver: bridge
